chessrook_project/chessrook/urls.py
from django.urls import path
from . import views

app_name = 'chessrook'

urlpatterns = [
	path("", views.home_screen, name="home_screen"),
	path("home_page", views.home_page, name="home_page"),
	path("serve_test_board/<str:id>", views.serve_test_board, name="serve_test_board"),
	path("serve_test_board_new_game", views.serve_test_board_new_game, name="serve_test_board_new_game"),
	path("test_board", views.test_board, name="test_board"), 
	path("exe_cmd", views.exe_cmd, name="exe_cmd"),
	path("serve_replay_board/<str:id>", views.serve_replay_board, name="serve_replay_board"),
	path("replay_board", views.replay_board, name="replay_board"),
	path("replay_exe_cmd", views.replay_exe_cmd, name="replay_exe_cmd"),
	path("update_game_details", views.update_game_details, name="update_game_details")
]

chessrook_project/chessrook_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name="profile"),
    path('profile_update/', user_views.profile_update, name="profile_update"),
    path('', include('chessrook.urls')),
]

chessrook_project/chessrook/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class ChessGames(models.Model):
    game_name = models.CharField(max_length=50) 
    # name of game
    game_play_monitor_instance = models.BinaryField() 
    # the game play state
    date_started = models.DateTimeField(default=timezone.now) 
    # the date when the game was created
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    # notes about the game
    game_notes = models.CharField(max_length=5000, default="none_notes")

    def __str__(self):
        return self.game_name

chessrook_project/chessrook/views.py
# Python imports
import pickle
import time

# Django imports
from django.shortcuts import render, redirect
from django import forms
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Django models imports
from chessrook.models import ChessGames
from django.contrib.auth.models import User

# Other imports
from . import gameplay

assets = {
    "~~": 'chessrook/chess_pieces/empty_square.png',

    "bR": 'chessrook/chess_pieces/black_rook.png',
    "bB": 'chessrook/chess_pieces/black_bishop.png',
    "bN": 'chessrook/chess_pieces/black_knight.png',
    "bQ": 'chessrook/chess_pieces/black_queen.png',
    "bK": 'chessrook/chess_pieces/black_king.png',
    "bP": 'chessrook/chess_pieces/black_pawn.png',

    "wR": 'chessrook/chess_pieces/white_rook.png',
    "wB": 'chessrook/chess_pieces/white_bishop.png',
    "wN": 'chessrook/chess_pieces/white_knight.png',
    "wQ": 'chessrook/chess_pieces/white_queen.png',
    "wK": 'chessrook/chess_pieces/white_king.png',
    "wP": 'chessrook/chess_pieces/white_pawn.png',
}

def convert_grid_to_dict(grid_board):
    dict_board = {}
    for row in range(0,8):
        for col in range(0,8):
            key = f"cell_{row}{col}"
            value = assets[grid_board[row][col]]
            dict_board[key] = value
    return dict_board    

class PlayerCommandForm(forms.Form):
    cmd = forms.CharField(label="cmd", widget=forms.TextInput(attrs={'id': 'cmd','type':'hidden'}))

class NewGameForm(forms.Form):
    game_name = forms.CharField(max_length=50, label="", widget=forms.TextInput(attrs={
        'id': 'game_name-id',
        'type':"text",
        'class':"form-control game-name",
        'placeholder':'Game Name (50 char or less)',
        'aria-describedby':'basic-addon2'
    }))

class GameEditForm(forms.Form):
    game_name_edit = forms.CharField(label="game_name_edit", widget=forms.TextInput(attrs={'id': 'game_name_edit-id','type':'hidden'}))
    game_notes_edit = forms.CharField(label="game_notes_edit", widget=forms.TextInput(attrs={'id': 'game_notes_edit-id','type':'hidden'}))

gameplay_monitor_instance_USER = -1
game_req_USER = -1
game_id_USER = -1
game_replay_snapshot_idx_USER = -1
game_replay_snapshot_len_USER = -1


class GameDisplay():
    def __init__(self, game_id, game_name, game_notes, game_time, status, status_detailed) -> None:
        self.id = game_id
        self.name = game_name
        self.notes = game_notes
        if len(self.notes) >= 184:
            self.mini_notes = game_notes[:184] # first 184 chracters of game notes
        else:
            self.mini_notes = game_notes
        self.time = game_time
        self.status = status
        self.status_detailed = status_detailed

# Create your views here.

def home_screen(request):
    if request.user.is_authenticated:
        return redirect('/home_page')
    else:
        return render(request, "chessrook/home_screen.html")


@login_required
def home_page(request):
    allGames = ChessGames.objects.filter(player=request.user)

    games = []
    for game_obj in allGames:
        gameplay_monitor_instance = pickle.loads(game_obj.game_play_monitor_instance)
        status_detailed = "NIL"
        print(gameplay_monitor_instance)
        if gameplay_monitor_instance.game_end == True:
            status = "Game Over"
            if gameplay_monitor_instance.white_won == True:
                status_detailed = "White Won"
            elif gameplay_monitor_instance.black_won == True:
                status_detailed = "Black Won"
            elif gameplay_monitor_instance.draw == True:
                status_detailed = "Draw"
        else:
            status = "Active"
        games.append(GameDisplay(game_obj.id, game_obj.game_name, game_obj.game_notes, game_obj.date_started, status, status_detailed))

    games.reverse()
    return render(request, "chessrook/home_page.html", {
        "form": NewGameForm(),
        "games": games
    })

@login_required
def serve_test_board(request, id):
    # convert this id str into int
    game_id_req = int(id)

    # obtain this game
    game_req_list = ChessGames.objects.filter(id=game_id_req)
    
    # check if such a valid game exists or not
    if len(game_req_list) == 0:
        # invalid game_id
        return render(request, "chessrook/invalid_game_id.html")
    else:
        # obtain game state
        game_req = game_req_list[0]
        
        # check if this game.player == request.user
        if game_req.player != request.user:
            return render(request, "chessrook/invalid_game_id.html")
        else:
            global game_req_USER
            global game_id_USER
            global gameplay_monitor_instance_USER
            
            game_req_USER = game_req
            game_id_USER = game_id_req
            gameplay_monitor_instance_USER = pickle.loads(game_req.game_play_monitor_instance)

            return HttpResponseRedirect(reverse("chessrook:test_board"))

@login_required
def serve_test_board_new_game(request):
    global game_req_USER
    global gameplay_monitor_instance_USER
        

    if request.method == "GET":
        current_timestamp = time.time()
        new_game_name = f"default_name_{current_timestamp}"
        new_gameplay_monitor_instance = gameplay.GamePlayMonitor()
        new_game_user = request.user
        new_game_req = ChessGames(game_name=new_game_name, game_play_monitor_instance=pickle.dumps(new_gameplay_monitor_instance),player=new_game_user)
        new_game_req.save()

        
        game_req_USER = new_game_req
        gameplay_monitor_instance_USER = new_gameplay_monitor_instance

        return HttpResponseRedirect(reverse("chessrook:test_board"))
    elif request.method == "POST":
        form = NewGameForm(request.POST)
        if form.is_valid():            
            new_game_name = form.cleaned_data["game_name"]
            new_gameplay_monitor_instance = gameplay.GamePlayMonitor()
            new_game_user = request.user
            new_game_req = ChessGames(game_name=new_game_name, game_play_monitor_instance=pickle.dumps(new_gameplay_monitor_instance),player=new_game_user)
            new_game_req.save()

            game_req_USER = new_game_req
            gameplay_monitor_instance_USER = new_gameplay_monitor_instance

            return HttpResponseRedirect(reverse("chessrook:test_board"))

@login_required
def test_board(request):
    global game_req_USER
    global game_id_USER
    global gameplay_monitor_instance_USER

    if game_req_USER == -1:
        return HttpResponseRedirect(reverse('chessrook:home_page'))
    
    game_id_USER = game_req_USER.id
    gameplay_monitor_instance_USER = pickle.loads(game_req_USER.game_play_monitor_instance)

    if gameplay_monitor_instance_USER.game_end == True:
        return redirect(f'/serve_replay_board/{game_id_USER}')
    
    status_detailed = "NIL"
    if gameplay_monitor_instance_USER.game_end == True:
        status = "Game Over"
        if gameplay_monitor_instance_USER.white_won == True:
            status_detailed = "White Won"
        elif gameplay_monitor_instance_USER.black_won == True:
            status_detailed = "Black Won"
        elif gameplay_monitor_instance_USER.draw == True:
            status_detailed = "Draw"
    else:
        status = "Active"
    
    game = GameDisplay(game_req_USER.id, game_req_USER.game_name, game_req_USER.game_notes, game_req_USER.date_started, status, status_detailed)

    master_dict = {}
    master_dict["game"] = game
    master_dict["form"] = PlayerCommandForm()
    master_dict["game_edit_form"] = GameEditForm()
    master_dict.update(convert_grid_to_dict(gameplay_monitor_instance_USER.gstate.board))
    
    bpc_raw = gameplay_monitor_instance_USER.gstate.black_pieces_captured
    bpc_processed = []
    for ele in bpc_raw:
        bpc_processed.append(assets[ele])

    wpc_raw = gameplay_monitor_instance_USER.gstate.white_pieces_captured
    wpc_processed = []
    for ele in wpc_raw:
        wpc_processed.append(assets[ele])

    game_snapshot_list = gameplay_monitor_instance_USER.game_snapshot_list
    white_moves_chess_notation_modified = []
    black_moves_chess_notation_modified = []
    for idx, game_snapshot in enumerate(game_snapshot_list):
        if idx == 0:
            continue
        
        if idx % 2 == 1:
            # white's move
            white_moves_chess_notation_modified.append(game_snapshot.chess_notation_modified)
        else:
            black_moves_chess_notation_modified.append(game_snapshot.chess_notation_modified)
    
    master_dict["white_moves"] = white_moves_chess_notation_modified
    master_dict["black_moves"] = black_moves_chess_notation_modified

    master_dict["bpc_1"] = bpc_processed[:len(bpc_processed)//2]
    master_dict["bpc_2"] = bpc_processed[len(bpc_processed)//2:]
    master_dict["wpc_1"] = wpc_processed[:len(wpc_processed)//2]
    master_dict["wpc_2"] = wpc_processed[len(wpc_processed)//2:]
    master_dict["value_black_captured"] = gameplay_monitor_instance_USER.gstate.value_black_captured
    master_dict["value_white_captured"] = gameplay_monitor_instance_USER.gstate.value_white_captured

    # this ensures that broswer reload is restricted to only two initiators:
    # 1. the initial loading done by serve_test_board/<str:id> route or serve_test_board_new_game
    # 2. the final auto reload at end of game done by Javascript
    game_req_USER = -1

    return render(request, "chessrook/test_board.html", master_dict)

@login_required
def update_game_details(request):
    if request.method == "POST":
        print("Received command via AJAX for edit of game details")
        game_name_edit = request.POST['game_name_edit']
        game_notes_edit = request.POST['game_notes_edit']
        gid = request.POST['gid']

        game_req_GAME = ChessGames.objects.filter(id=gid).first()

        game_req_GAME.game_name = game_name_edit

chessrook_project/chessrook/templates/chessrook/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'chessrook/styles.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<style>
    .navbar{
        margin-bottom: 10px;
        height: 60px;
    }

    .navbar-brand{
        margin-left: 10px;
        font-size: 20px;
        font-weight: bold;
        width: 50%;
        text-align: left;
    }

    .login-btn{
        margin-right: 0;
    }

    .profile-btn{
        margin-right: 0;
    }

    .register-btn{
        margin-left: 0;
        margin-right: 10px;
    }

    .logout-btn{
        margin-right: 10px;
    }

    .btn-system{
        width: 40%;
        text-align: right;
    }

    @media only screen and (max-width:500px){
        .navbar{
            margin-bottom: 10px;
            height: 60px;
        }

        .navbar-brand{
            margin-left: 10px;
            font-size: 20px;
            font-weight: bold;
            width: 30%;
            text-align: left;
        }

        .login-btn{
            margin-right: 0;
        }

        .profile-btn{
            margin-right: 0;
        }

        .register-btn{
            margin-left: 0;
            margin-right: 2px;
        }

        .logout-btn{
            margin-right: 2px;
        }

        .btn-system{
            width: 50%;
            text-align: right;
        }
    }
</style>

<body>
    <nav class="navbar navbar-dark bg-dark">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'chessrook:home_page' %}">Chessrook</a>    
        {% else %}
            <a class="navbar-brand" href="{% url 'chessrook:home_screen' %}">Chessrook</a>    
        {% endif %}
        
        
        <div class="btn-system">
            {% if user.is_authenticated %}
                <a href="{% url 'profile' %}" class="btn btn-outline-warning profile-btn">Profile</a>    
                <a href="{% url 'logout' %}" class="btn btn-outline-danger logout-btn">Logout</a>                
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-outline-success login-btn">Login</a>
                <a href="{% url 'register' %}" class="btn btn-outline-primary register-btn">Register</a>
            {% endif %}
        </div>
        
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}{% endblock %}
</body>
</html>

chessrook_project/chessrook/templates/chessrook/home_page.html
{% extends 'chessrook/base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <style>
        form{
            width: 400px;
            margin-left: auto;
            margin-right: auto;
        }

        @media only screen and (max-width:500px){
            form{
                width: 360px;
                margin-left: auto;
                margin-right: auto;
            }
        }

        /* Responsive Design for game grids */

        @media only screen and (max-width: 1445px){
            .col-sm-6{
                margin-top: 10px;
            }
        }

        @media only screen and (min-width: 1445px){
            .col-sm-6{
                width: 500px;
                margin-left: auto;
                margin-right: auto;
                margin-top: 10px;
            }
        }

        .row{
            width: 90%;
            margin-left: auto;
            margin-right: auto;
        }

        
        @media only screen and (max-width:1669px){
            /* screen width <= 1669 px */
            .row{
                width: 70%;
                margin-left: auto;
                margin-right: auto;
            }
        }
    </style>

    <h1 style="margin-bottom: 20px; margin-left: 10px;">Homepage</h1>
    <form action="{% url 'chessrook:serve_test_board_new_game' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            {{ form.game_name }}
            <div class="input-group-append">
                <button class="btn btn-outline-success" type="submit">New Game</button>
            </div>
        </div>
    </form>

    <div class="row">
        {% for game in games %} 
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card text-center mb-3">
              <div class="card-body">                
                {% if game.status_detailed == "Black Won" %}
                <h5 class="card-title">{{ game.name }} <span class="badge bg-danger">{{ game.id }}</span> <span class="badge bg-warning">{{ game.status }}</span> <span class="badge bg-dark">Black Won</span> </h5>
                {% elif game.status_detailed == "White Won" %}
                <h5 class="card-title">{{ game.name }} <span class="badge bg-danger">{{ game.id }}</span> <span class="badge bg-warning">{{ game.status }}</span> <span class="badge text-bg-light">White Won</span> </h5>                
                {% elif game.status_detailed == "Draw" %}
                <h5 class="card-title">{{ game.name }} <span class="badge bg-danger">{{ game.id }}</span> <span class="badge bg-warning">{{ game.status }}</span> <span class="badge bg-secondary">Draw</span> </h5>
                {% else %}
                <h5 class="card-title">{{ game.name }} <span class="badge bg-danger">{{ game.id }}</span> <span class="badge bg-warning">{{ game.status }}</span> </h5>
                {% endif %}
                <h6 class="card-title">{{ game.time }}</h6>
                <!-- We are displaying the first 184 characters of game notes in this below p section -->
                <p class="card-text">{{ game.mini_notes }} ...</p>
                {% if game.status == "Active" %}
                    <a href="{% url 'chessrook:serve_test_board' game.id %}" class="btn btn-success">Resume</a>
                {% else %}
                    <a href="{% url 'chessrook:serve_replay_board' game.id %}" class="btn btn-primary">Analyze</a>
                {% endif %}
                
                
              </div>
            </div>
          </div>
        {% empty %}
        <div class="alert alert-primary" role="alert" style="text-align: center; width: 60%; margin-left: auto; margin-right: auto;">
            You don't have any Games played. Play a New Game Now !
          </div>
        {% endfor %}
    </div>
    
{% endblock content %}

chessrook_project/chessrook/templates/chessrook/home_screen.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Chessrook</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'chessrook/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Chessrook</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0" href="{% url 'login' %}">Login</a>
        <a class="nav-link fw-bold py-1 px-0" href="{% url 'register' %}">Register</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>Your one stop destination for Chess Analysis.</h1>
    <p class="lead">Whether you want to play a relaxing game of chess with yourself, or are practicing the day before your big tournament, Chessrook has got you covered with a full fledged Chess Engine and Analysis tools all packed in a wonderful and easy to use UI.</p>
    <p class="lead">
      <a href="{% url 'register' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Register Today</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Chessrook Web Application is designed and created by Arghyadeep Acharya for educational purpose only.</p>
  </footer>
</div>


    
  </body>
</html>

chessrook_project/chessrook/templates/chessrook/invalid_game_id.html
{% extends 'chessrook/base.html' %}
{% load static %}

{% block title %}
    Invalid Game ID
{% endblock title %}

{% block navbar %}
    Hello this is Nav Bar
{% endblock navbar %}

{% block content %}
    <h1>Invalid Game ID entered</h1>
{% endblock content %}